params:
    mysql:
      host: localhost
      driver: pdo_mysql
      dbname: tms
      user: root
      password: root
    mssql:
      host: localhost
      driver: pdo_mysql
      dbname: tms
      user: root
      password: root
    mapping:
      - { source: tombstone, destination: objects }
