services:
  tmssync.main:
    class: Flemishartcollection\TMSSync\Main
    arguments: ['@console.application']
    calls:
      - [setInstaller, ['@flemishartcollection.installer']]
      - [setExporter, ['@flemishartcollection.exporter']]
  flemishartcollection.exporter:
    class: Flemishartcollection\TMSSync\Exporter
  flemishartcollection.installer:
    class: Flemishartcollection\TMSSync\Installer
  console.application:
    class: Symfony\Component\Console\Application
