parameters:
  schema_file: '%kernel.project_dir%/schema.sql'
  source:
    table_prefix: 'dbo.'
    host: '%env(SOURCE_HOST)%'
    driver: pdo_sqlsrv
    dbname: '%env(SOURCE_DB)%'
    user: '%env(SOURCE_USER)%'
    password: '%env(SOURCE_PASSWORD)%'
    charset: utf8mb4
    driverOptions:
      Encrypt: true
      TrustServerCertificate: true
  destination:
    host: '%env(DEST_HOST)%'
    driver: pdo_mysql
    dbname: '%env(DEST_DB)%'
    user: '%env(DEST_USER)%'
    password: '%env(DEST_PASSWORD)%'
    charset: utf8mb4
  tables:
    - Objects
    - ObjContext
    - ObjectNames
    - ClassificationXRefs
    - Classifications
    - DimItemElemXrefs
    - Dimensions
    - DimensionElements
    - DimElemTypeXrefs
    - DimensionTypes
    - DimUnitTypes
    - DimensionUnits
    - DimensionMethods
    - DDLanguages
    - Constituents
    - ConAltNames
    - ConXrefs
    - ConXrefDetails
    - Roles
    - RoleTypes
    - TextTypes
    - TextEntries
    - TextStatuses
    - ThesXrefs
    - ThesXrefTypes
    - ThesaurusBases
    - TermClasses
    - TermMaster
    - Terms
    - UserFieldXrefs
    - ObjTitles
    - TitleTypes
    - CITvgsrpObjTombstoneD_RO
    - Departments
    - Associations
    - Relationships
    - AltNums
    - AltNumDescriptions
    - Locations
    - ObjLocations
    - ObjComponents
    - MediaXrefs
    - MediaRenditions
    - MediaFiles
    - ClassificationNotations
    - StatusFlags
    - AuthorityTranslations
    - TermMasterThes
    - Exhibitions
    - ExhibitionTitles
    - ExhObjXrefs
    - HistEvents
    - VGSRPCONDITIONSS_RO
    - vgsrpSurveyTypesS_RO
    - vgsrpSurveyAttrTypesS_RO
    - vgsrpCondLineItemsS_RO
    - VGSRPMEDIAMASTERS_RO
    - MediaPaths
    - OSCCitaatvormen
